### ISSUE TITLE
how to setting configuration option??

### ISSUE THREAD

**Issue by sulho** [MinecraftModDevelopment/LootableBodies#18]
I don't know how to  set configuration options

please tell me

**Comment by dshadowwolf** [comment]
I believe you might have missed the ``config`` folder that is alongside the ``mods`` folder where you installed this mod. In that is a file that is called either ``lootablebodies.cfg`` or ``lootable_bodies.cfg`` (I do not recall which) that contains all the configuration options for this mod.

Unless things have changed since I last looked at this mods code, there is no in-game gui for managing the config options and I apologize for that lack but I am only tangentially on the team for this mod, though I have tried to do some work to clean up its code and find and remove some really nasty bugs that it has.
